<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>SolutionColors</RootNamespace>
    <AssemblyName>SolutionColors</AssemblyName>
    <Version>1.1.999</Version>
    <AssemblyTitle>Solution Colors</AssemblyTitle>
    <Description>Allows you to associate a color with a solution and display it in various locations within Visual Studio. Inspired by the Peacock extension for VS Code.</Description>
    <Company>Mads Kristensen</Company>
    <Product>Solution Colors</Product>
    <Copyright>Mads Kristensen</Copyright>

    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <CreateVsixContainer>true</CreateVsixContainer>
    <DeployExtension>false</DeployExtension>
    <VsixDeployOnDebug>true</VsixDeployOnDebug>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>true</IncludeDebugSymbolsInVSIXContainer>

    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Community.VisualStudio.VSCT" Version="16.0.29.6" PrivateAssets="all" />
    <PackageReference Include="Community.VisualStudio.Toolkit.17" Version="17.0.555" ExcludeAssets="Runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Telemetry" Version="16.4.78" />
    <PackageReference Include="Microsoft.VisualStudio.Workspace.VSIntegration" Version="16.0.59" ExcludeAssets="Runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.12.465" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Design" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\LICENSE" Link="Resources\LICENSE" IncludeInVSIX="true" />
    <None Remove="Resources\Icon.png" />
    <Content Include="Resources\Icon.png" IncludeInVSIX="true" />
    <None Update="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
      <Generator>VsixManifestGenerator</Generator>
      <LastGenOutput>source.extension.cs</LastGenOutput>
    </None>
    <Compile Update="source.extension.cs">
      <AutoGen>true</AutoGen>
      <DesignTime>true</DesignTime>
      <DependentUpon>source.extension.vsixmanifest</DependentUpon>
    </Compile>
    <VSCTCompile Include="VSCommandTable.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
      <Generator>VsctGenerator</Generator>
      <LastGenOutput>VSCommandTable.cs</LastGenOutput>
    </VSCTCompile>
    <Compile Update="VSCommandTable.cs">
      <AutoGen>true</AutoGen>
      <DesignTime>true</DesignTime>
      <DependentUpon>VSCommandTable.vsct</DependentUpon>
    </Compile>
    <Compile Update="Options\BorderEditorDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Options\BorderEditorDialog.Designer.cs">
      <DependentUpon>BorderEditorDialog.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Options\BorderEditorDialog.resx">
      <DependentUpon>BorderEditorDialog.cs</DependentUpon>
    </EmbeddedResource>
    <InternalsVisibleTo Include="SolutionColors.Test" />
  </ItemGroup>

</Project>
