// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionColors
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SolutionColorsString = "3a113b17-c53c-45f0-baab-571abef8b325";
        public static Guid SolutionColors = new Guid(SolutionColorsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OuterGroup = 0x0001;
        public const int InnerGroup = 0x0002;
        public const int FlyoutMenu = 0x1000;
        public const int Blue = 0x0100;
        public const int Red = 0x0110;
        public const int Green = 0x0120;
        public const int Turquoise = 0x0130;
        public const int Purple = 0x0140;
        public const int None = 0x0222;
    }
}