// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionColors
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SolutionColorsString = "3a113b17-c53c-45f0-baab-571abef8b325";
        public static Guid SolutionColors = new Guid(SolutionColorsString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);

        public const string TabColorsString = "a1fa08e5-519b-4810-bdb0-89f586af37e9";
        public static Guid TabColors = new Guid(TabColorsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OuterGroup = 0x0001;
        public const int InnerGroup = 0x0002;
        public const int NoneGroup = 0x0003;
        public const int AnyCodeGroup = 0x0004;
        public const int OptionsGroup = 0x0005;
        public const int FlyoutMenu = 0x1000;
        public const int Lavender = 0x0100;
        public const int Gold = 0x0101;
        public const int Cyan = 0x0102;
        public const int Burgundy = 0x0103;
        public const int Green = 0x0104;
        public const int Brown = 0x0105;
        public const int RoyalBlue = 0x0106;
        public const int Pumpkin = 0x0107;
        public const int Gray = 0x0108;
        public const int Volt = 0x0109;
        public const int Teal = 0x0110;
        public const int Magenta = 0x0111;
        public const int Mint = 0x0112;
        public const int DarkBrown = 0x0113;
        public const int Blue = 0x0114;
        public const int Pink = 0x0115;
        public const int Custom = 0x0190;
        public const int None = 0x0200;
        public const int Options = 0x0300;
        public const int idmWSE_ContextMenu = 0x0002;
        public const int cLavender = 0x0001;
        public const int cGold = 0x0002;
        public const int cCyan = 0x0003;
        public const int cBurgundy = 0x0004;
        public const int cGreen = 0x0005;
        public const int cBrown = 0x0006;
        public const int cRoyalBlue = 0x0007;
        public const int cPumpkin = 0x0008;
        public const int cGray = 0x0009;
        public const int cVolt = 0x000A;
        public const int cTeal = 0x000B;
        public const int cMagenta = 0x000C;
        public const int cMint = 0x000D;
        public const int cDarkBrown = 0x000E;
        public const int cBlue = 0x000F;
        public const int cPink = 0x0010;
    }
}